### ISSUE TITLE
Download button crashing chrome

### ISSUE THREAD

**Issue by suthar26** [Vexilla/app#16]
I tried downloading the configs a couple time and it crashed chrome. 
  - 3 times (2 with the following configs and once with the hosting configs)

<img width="1606" alt="Screenshot 2023-04-10 at 10 31 00 PM" src="https://user-images.githubusercontent.com/8922654/231040246-aa8d2730-1743-4bbf-9822-820d13368cfa.png">

I was able to copy the json and it is pasted below

```json
{
  "environments": {
    "test": {
      "untagged": {
        "feature1": {
          "value": true,
          "type": "toggle"
        },
        "feature2": {
          "value": false,
          "type": "toggle"
        }
      }
    },
    "staging": {
      "untagged": {
        "feature1": {
          "value": false,
          "type": "toggle"
        },
        "feature2": {
          "value": true,
          "type": "toggle"
        }
      }
    }
  }
}
```

**Comment by cmgriffing** [comment]
I think I can finally start digging into this. What OS and version of Chrome did you use?

**Comment by suthar26** [comment]
Sorry for this, but I think this may have been an issue on my end. I encountered the same with other downloads on Chrome. 

Closing for that reason, for future reference. OS: MacOS Ventura 13.1 and Chrome version not recorded but it was latest version
