### ISSUE TITLE
"Randomise" button fails /#/environment/localdev2

### ISSUE THREAD

**Issue by prawnsalad** [Vexilla/app#2]
In an environment, under the  "Gradual" section, click the randomize button. "Uncaught TypeError: _ctx.randomizeSeed is not a function"

**Comment by prawnsalad** [comment]
Also happens if I use the slider but not in 100% cases


+ on the "Threshhold" slider. (typo in the label?)

**Comment by cmgriffing** [comment]
Thanks for catching this.

Fixed with commit:
https://github.com/Vexilla/app/commit/24a6a983c6922e3b5841a9cd657c6aa2ac7df77d
