### ISSUE TITLE
Duplicate feature names accepted

### ISSUE THREAD

**Issue by prawnsalad** [Vexilla/app#9]
Possibly an allowed feature - but when adding a new feature then duplicate names are allowed which causes confusing items in the list

**Comment by cmgriffing** [comment]
I think this is something we need to prevent. 

In the future, FeatureSets might be a way for features to have same names but not interfere with each other.

Fixed by commit:
https://github.com/Vexilla/app/commit/70489abd67a8addf02133b213e2933d39232855c
